project_id = "wooailayahufzjwfvypz"

[api]
  enabled = true
  extra_search_path = ["public", "extensions"]
  max_rows = 1000
  port = 54321
  schemas = ["public", "graphql_public"]

[auth]
  additional_redirect_urls = ["https://127.0.0.1:3000"]
  enable_anonymous_sign_ins = false
  enable_signup = true
  enabled = true
  jwt_expiry = 3600
  port = 54324
  refresh_token_rotation_enabled = true
  security_refresh_token_reuse_interval = 10
  site_url = "http://127.0.0.1:3000"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-client]
    verify_jwt = true
  [functions.link-client]
    verify_jwt = true
  [functions.list-clients]
    verify_jwt = true
  [functions.place-order]
    verify_jwt = true
  [functions.update-client-status]
    verify_jwt = true
